version: 2

models:
  - name: stg_bookings
    description: 'Cleaned, transformed table having everything about the bookings'
    columns:
      - name: BOOKING_ID
        tests:
          - unique
          - not_null

      - name: LISTING_ID
        tests:
          - not_null
          - relationships:
              to: ref('stg_listings')
              field: LISTING_ID

      - name: BOOKING_DATE
        tests:
          - not_null

      - name: BOOKING_STATUS
        tests:
          - booking_test



  - name: stg_hosts
    description: 'Cleaned, transformed table having everything about the hosts'
    columns:
      - name: HOST_ID
        tests:
          - unique
          - not_null

      - name: HOST_NAME
        tests:
          - not_null
        
      - name: IS_SUPERHOST
        tests:
          - not_null



  - name: stg_listings
    description: 'Cleaned, transformed table having everything about the listings'
    columns:
      - name: LISTING_ID
        tests:
          - unique
          - not_null

      - name: HOST_ID
        tests:
          - not_null
          - relationships:
              to: ref('stg_hosts')
              field: HOST_ID

      - name: PROPERTY_TYPE
        tests:
          - listing_test_1

      - name: ROOM_TYPE
        tests:
          - listing_test_2